services:
  nextqt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextqt
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
    networks:
      Ex_V1:
        ipv4_address: 172.19.0.6


networks:
  Ex_V1:
    name: V1
    external: true
    ipam:
      driver: default
      config:
        - subnet: "172.19.0.0/16"